### ISSUE TITLE
HEADLESS_IDA Windows Server

### ISSUE THREAD

**Issue by rtompsam** [DennyDai/headless-ida#3]
Sorry just noticed the normal python  standalone module works but when running through the server getting same Exception,.

**Comment by rtompsam** [comment]
>>> headlessida = HeadlessIdaRemote("localhost", 1337, r'C:\Users\me\Desktop\IDAPYTHON\test.exe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\headless_ida\client.py", line 82, in __init__
    self.conn.root.init(f.read())
  File "C:\Program Files\Python38\lib\site-packages\rpyc\core\netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "C:\Program Files\Python38\lib\site-packages\rpyc\core\netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "C:\Program Files\Python38\lib\site-packages\rpyc\core\protocol.py", line 718, in sync_request
    return _async_res.value
  File "C:\Program Files\Python38\lib\site-packages\rpyc\core\async_.py", line 108, in value
    raise self._obj
Exception: IDA failed to start: return code 1
=============== STDOUT ===============
=============== STDERR ===============


========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\rpyc\core\protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "c:\program files\python38\lib\site-packages\rpyc\core\protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
  File "c:\program files\python38\lib\site-packages\headless_ida\server.py", line 29, in exposed_init
    raise Exception(
Exception: IDA failed to start: return code 1
=============== STDOUT ===============
=============== STDERR ===============

PORT IS OPEN TCP    127.0.0.1:1337         0.0.0.0:0              LISTENING       6888

**Comment by DennyDai** [comment]
TIL https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile doesn't work as expected on windows...
Working on a fix

**Comment by rtompsam** [comment]
Ahh ok just noticed that the issue is with opening the file thanks !!

**Comment by DennyDai** [comment]
There are more issues than I thought... I've just fixed that TempFile issue and it's now on PyPi (0.4.4). Tested locally and it works.
Please make sure when you are running the server, path to idat64 should not contain a space for now, I will fix this later.

**Comment by rtompsam** [comment]
Awesome thanks working :)
